DATABASE_NAME = "quality_monitor.db"

EXCELLENT_THRESHOLD = 95
GOOD_THRESHOLD = 85
WARNING_THRESHOLD = 70

MAX_MISSING_RATE = 5.0
MAX_DUPLICATE_RATE = 2.0
MAX_OUTLIER_RATE = 3.0

STRICT_SCHEMA_VALIDATION = True


EXPECTED_COLUMNS = [
    "order_id",
    "customer_id",
    "amount",
    "quantity"
]